# Generated by Django 2.0.4 on 2018-04-25 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20180418_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
