# Generated by Django 2.0.4 on 2018-04-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pos',
            new_name='account_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
